org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.caching=true

minecraft_version=1.20.1
forge_version=47.2.32

mod_id=dydanmakuforge
mod_name=DyDanmaku Forge
mod_license=All Rights Reserved
mod_version=0.1.7.2
mod_group_id=top.tiangalon
mod_authors=tiangalon
mod_description=一个用于在 Minecraft 聊天框接收抖音直播弹幕的客户端模组
