org.gradle.jvmargs=-Xmx4G
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)
neo_version=21.1.244
neo_version_range=[21.1.244,)
loader_version_range=[1,)

mod_id=dydanmakuforge
mod_name=DyDanmaku NeoForge
mod_license=All Rights Reserved
mod_version=0.1.7.2
mod_group_id=top.tiangalon
mod_authors=tiangalon
mod_description=\u4e00\u4e2a\u7528\u4e8e\u5728 Minecraft \u804a\u5929\u6846\u63a5\u6536\u6296\u97f3\u76f4\u64ad\u5f39\u5e55\u7684 NeoForge \u5ba2\u6237\u7aef\u6a21\u7ec4
