modLoader="javafml"
loaderVersion="[0,)"
license="${mod_license}"
clientSideOnly=true

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/tiangalon/DyDanmakuForge"
logoFile="assets/dydanmaku/icon.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[52,)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="CLIENT"
